language: scala
scala:
  - 2.12.0
jdk:
  - oraclejdk8
sudo: false
script:
  - for i in `seq 1 10` ; do echo $i ; git clean -fdx ; sbt ++$TRAVIS_SCALA_VERSION test ; done
addons:
  apt:
    packages:
    - oracle-java8-installer
